##
## pgmon agent configuration sample (non-secret)
## ---------------------------------------------------------------------
## Copy this file to `config.pgmon.yaml`, adjust the metadata, and keep
## it under version control. Runtime secrets (DSNs, webhook tokens, etc.)
## belong in `.env` or your secret manager, not in this file.
##

# Logical label for this Postgres environment (appears in metrics, logs, UI).
# Pick something meaningful like "prod-eu-west" or "analytics-cluster".
cluster: "prod-eu-west-cluster"

sample_intervals:
  # Hot-path loop: sessions, locks, autovacuum progress (default 15s).
  hot_path: "15s"
  # Workload loop: TPS/QPS, top statements, WAL (default 60s).
  workload: "60s"
  # Storage loop: Top-N relations, dead tuple backlog (default 10m).
  storage: "10m"
  # Hourly loop: bloat estimates, wraparound safety (default 1h).
  hourly: "1h"

limits:
  # Top-N guards on relation, index, and query metrics.
  top_relations: 50
  top_indexes: 50
  top_queries: 50
  # Number of days ahead to examine partition boundaries.
  partition_horizon_days: 7

bloat:
  # Bloat sampling mode: "approx" (pgstattuple_approx, fast),
  # "exact" (pgstattuple, slower but accurate), or "detailed" (pageinspect, most detailed).
  sampling_mode: "exact"
  # Number of largest tables to analyze with advanced bloat sampling.
  top_n_tables: 10
  # Enable pageinspect for heap-level fragment analysis (requires pageinspect extension).
  enable_pageinspect: false
  # Minimum reclaimable bytes to recommend VACUUM FULL (default: 104857600 = 100 MB).
  # Prevents recommending VACUUM FULL for tiny tables where the overhead outweighs the benefit.
  min_reclaim_bytes: 104857600

alerts:
  connections_warn: 0.80
  connections_crit: 0.95
  long_txn_warn_s: 300
  long_txn_crit_s: 1800
  repl_warn_s: 30
  repl_crit_s: 300
  stats_stale_warn_hours: 12
  stats_stale_crit_hours: 24
  wraparound_warn_tx_age: 1500000000
  wraparound_crit_tx_age: 1800000000
  wal_surge_warn_bytes_per_sec: 104857600
  wal_surge_crit_bytes_per_sec: 209715200
  temp_surge_warn_bytes_per_sec: 52428800
  temp_surge_crit_bytes_per_sec: 104857600
  autovac_starvation_warn_hours: 6
  autovac_starvation_crit_hours: 12
  checkpoint_ratio_warn: 0.2
  checkpoint_ratio_crit: 0.5
  checkpoint_interval_warn_seconds: 300
  checkpoint_interval_crit_seconds: 180

notifiers:
  # Optional: Slack webhook URL for alert notifications.
  slack_webhook: ""
  # Optional: SMTP connection string (e.g. smtp://user:pass@smtp.example.com:587?encryption=starttls).
  email_smtp: ""

http:
  bind: "0.0.0.0:8181"
  # Path inside the container where the React/Vite bundle is served from.
  static_dir: "/opt/pgmon/ui"

security:
  read_only_enforce: true
  redact_sql_text: true

ui:
  # Hide built-in postgres/template databases from wraparound panels (postgres, template0, template1).
  hide_postgres_defaults: true

timeouts:
  statement_timeout_ms: 3000
  lock_timeout_ms: 1000
